
const SET_LOGIN = 'SET_LOGIN';
const SET_PATIENT = 'SET_PATIENT';
const UPDATE_PATIENT = 'UPDATE_PATIENT';
const DELETE_PATIENT = 'DELETE_PATIENT';
const ADD_PATIENT = 'ADD_PATIENT';
export {
        SET_LOGIN,
        SET_PATIENT,
        UPDATE_PATIENT,
        DELETE_PATIENT,
        ADD_PATIENT,
}